# Habilita o uso das bibliotecas modernas do AndroidX
android.useAndroidX=true

# Converte automaticamente bibliotecas antigas para o padrão AndroidX
android.enableJetifier=true

# Otimizações de compilação (opcional, mas recomendado para ficar mais rápido)
org.gradle.jvmargs=-Xmx2048m -Dfile.encoding=UTF-8
